core/urls.py
from django.urls import path
from django.views.generic import RedirectView

from .views import dashboard, UserCreate, ProjectCreate, ProjectMemberCreate, TicketCreate, project_detail, delete_ticket, update_ticket_status

app_name = 'core'

urlpatterns = [
    path('', RedirectView.as_view(url='dashboard/')),
    path('dashboard/', dashboard, name='dashboard'),
]

urlpatterns += [
    path('user/create/', UserCreate, name='user-create'),
]

urlpatterns += [
    path('project/create/', ProjectCreate.as_view(), name='project-create'),
    path('projectmember/create/', ProjectMemberCreate.as_view(), name='projectmember-create'),
    path('ticket/create/', TicketCreate.as_view(), name='ticket-create'),
    path('project/<int:pk>', project_detail, name='project-detail'),
    path('ticket/<str:pk>/delete', delete_ticket, name='ticket-delete'),
    path('ticket/<str:pk>/update-status', update_ticket_status, name='ticket-update-status'),
]

sms/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView
from .views import login_view, logout_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='/login/')),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('core/', include('core.urls', namespace='core')),
]

admin.site.site_header = 'SMS'

core/models.py
from enum import unique
import uuid

from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

STATUS = (
    ('i', 'Initialized'),
    ('w', 'Working'),
    ('c', 'Complete'),
)
# Create your models here.
# class Technology(models.Model):
#     """Model representing a Technology (e.g. Python, Angular etc.)"""
#     name = models.CharField(max_length=50,
#                             help_text="Enter technologies (e.g. Python, Angular etc.)")

#     def __str__(self):
#         """String for representing the Model object (in Admin site etc.)"""
#         return self.name


class Project(models.Model):
    name = models.CharField(max_length=100)
    start_date = models.DateField('Start Date')
    end_date = models.DateField('End Date')
    
    status = models.CharField(max_length=1, choices=STATUS, default='i', help_text='Current Status')
    short_desc = models.CharField('Short Description', max_length=255, help_text='Short Description')
    description = models.TextField()

    def __str__(self) -> str:
        return self.name

    def get_absolute_url(self):
        return reverse('core:dashboard')
    

class ProjectMember(models.Model):
    project = models.ForeignKey(Project, on_delete=models.SET_NULL, null=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    
    # def __str__(self) -> str:
    #     return f'Member of - {self.project.name}'

    class Meta:
        verbose_name_plural = 'Project Members'
        constraints = [
            models.UniqueConstraint(name='unique_member', fields=['project', 'user'])
        ]

    def get_absolute_url(self):
        return reverse('core:projectmember-create')

class Ticket(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular ticket across whole system')
    project = models.ForeignKey(Project, on_delete=models.SET_NULL, null=True)
    status = models.CharField(max_length=1, choices=STATUS, default='i', help_text='Current Status')
    user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    details = models.CharField(max_length=255)
    date_i = models.DateField('Date Initialized', auto_now=True)
    date_w = models.DateTimeField('Date Working', null=True, blank=True)
    date_c = models.DateTimeField('Date Complete', null=True, blank=True)

    class Meta:
        permissions = (('can_mark_working', 'Set ticket as working'),('can_mark_complete', 'Set ticket as complete'),)

    def get_absolute_url(self):
        return reverse('core:ticket-create')


class UserActivity(models.Model):
    user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    ticket = models.ForeignKey(Ticket, null=True, on_delete=models.SET_NULL)
    action_date = models.DateTimeField('Datetime', auto_now=True)
    action = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = 'User Activities'


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    designation = models.CharField(max_length=50, null=True, blank=True, default='Employee')
    SEX_CHOICE = (
        ('m', 'Male'),
        ('f', 'Female'),
    )
    sex = models.CharField('Gender', max_length=1, choices=SEX_CHOICE, default='m')

core/forms.py
from django import forms
from .models import Ticket


class TicketStatusForm(forms.ModelForm):
    class Meta:
        model = Ticket
        fields = ('status', 'id')

core/views.py
import datetime

from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.views.generic import detail
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse, reverse_lazy

from .models import Project, ProjectMember, Ticket
from .utils import log_action, get_profile, get_user_permissions
from .forms import TicketStatusForm


@login_required
def dashboard(request):
    projects = Project.objects.raw(f"SELECT id, name FROM core_project WHERE id IN(SELECT project_id FROM core_projectmember WHERE user_id={request.user.id})")
    btn_choices = ('primary','success','info', 'warning', 'secondary', 'danger', 'dark')
    page_heading = 'Dashboard' if request.GET.get('p') is None else 'My Projects'
    permissions = get_user_permissions(request.user)
    context = {
        'profile': get_profile(request.user.id),
        'projects': projects,
        'btn_choices': btn_choices,
        'permissions': permissions,
        'page_heading': page_heading,
    }
    if 'core.can_mark_working' in permissions:
        template = 'core/dashboard2.html'
        context['tickets'] = Ticket.objects.select_related('user', 'project').filter(user=request.user.id)
    else:
        template = 'core/dashboard.html'
    return render(request, template, context)


@login_required
@permission_required('auth.add_user', raise_exception=True)
def UserCreate(request):
    if request.method == 'POST':
        f = UserCreationForm(request.POST)
        if f.is_valid():
            f.save()
            messages.success(request, 'Account created successfully')
            log_action(request.user.id, message=f'Add user. Username: {request.POST.get("username")}')
            return HttpResponseRedirect(reverse('core:user-create'))            
        else:
            messages.error(request, 'Account creation failed')
    else:
        f = UserCreationForm()
    context = {
        'profile': get_profile(request.user.id),
        'form': f,
        'permissions': get_user_permissions(request.user)
    }
    return render(request, 'core/user-register.html', context)


class ProjectCreate(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    permission_required = 'core.add_project'
    raise_exception = True
    model = Project
    fields = '__all__'

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            super().form_valid(form)
            #log action
            log_action(request.user.id, message=f'Add project. Project: {self.object.name}')
            #add member association
            pm = ProjectMember(project=self.object, user=request.user)
            pm.save()
            messages.success(request, 'Project created successfully')            
        else:
            messages.error(request, 'Project creation failed')
        return HttpResponseRedirect(reverse('core:project-create'))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['profile'] = get_profile(self.request.user.id)
        context['permissions'] = get_user_permissions(self.request.user)
        return context


class ProjectMemberCreate(PermissionRequiredMixin, LoginRequiredMixin, CreateView):
    permission_required = 'core.add_projectmember'
    raise_exception = True
    model = ProjectMember
    fields = '__all__'

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            super().form_valid(form)
            #log action
            log_action(request.user.id, message=f'Add project member. Project: {self.object.project}, User: {self.object.user}')
            messages.success(request, 'Add project member success')            
        else:
            messages.error(request, form.errors)
        return HttpResponseRedirect(reverse('core:projectmember-create'))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['profile'] = get_profile(self.request.user.id)
        context['permissions'] = get_user_permissions(self.request.user)
        return context


class TicketCreate(PermissionRequiredMixin, LoginRequiredMixin, CreateView):
    permission_required = 'core.add_ticket'
    raise_exception = True
    model = Ticket
    fields = ['id', 'project', 'user', 'details']

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            super().form_valid(form)
            #log action
            log_action(request.user.id, message=f'Add ticket. Project: {self.object.project}, User: {self.object.user}')
            messages.success(request, 'Add ticket success')
        else:
            messages.error(request, form.errors)
        return HttpResponseRedirect(reverse('core:ticket-create'))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['profile'] = get_profile(self.request.user.id)
        context['permissions'] = get_user_permissions(self.request.user)
        return context


@login_required
def project_detail(request, pk):
    project = get_object_or_404(Project, pk=pk)
    members = ProjectMember.objects.raw(f"SELECT id, username, first_name, last_name FROM auth_user WHERE id IN(SELECT user_id FROM core_projectmember WHERE project_id={pk})")
    tickets = Ticket.objects.select_related('user', 'project').filter(project=pk)
    expired = project.end_date < datetime.date.today() and project.status != 'c'
    context = {
        'profile': get_profile(request.user.id),
        'project': project,
        'permissions': get_user_permissions(request.user),
        'expired': expired,
        'members': members,
        'tickets': tickets
    }    
    return render(request, 'core/project-detail.html', context)


@login_required
@permission_required('core.delete_ticket', raise_exception=True)
def delete_ticket(request, pk):
    object = get_object_or_404(Ticket, pk=pk)
    
    if request.method =="POST":
        redirect = request.POST.get('redirect_to')
        #log action
        log_action(request.user.id, message=f'Delete ticket. Project: {object.project},  User: {object.user}, Ticket: {object.id}')
        object.delete()
        return HttpResponseRedirect(redirect)

    context = {
        'profile': get_profile(request.user.id),
        'permissions': get_user_permissions(request.user),
        'redirect_url': request.META.get('HTTP_REFERER')
    }
    return render(request, "core/ticket_delete.html", context)


@login_required
@permission_required('core.can_mark_complete', raise_exception=True)
def update_ticket_status(request, pk):
    ticket = get_object_or_404(Ticket, pk=pk)
    if request.method =="POST":
        ticket.status = request.POST['status']
        ticket.save()
    return HttpResponseRedirect(request.POST['redirect_to'])


@login_required
@permission_required('core.can_mark_working', raise_exception=True)
def update_ticket_status(request, pk):
    ticket = get_object_or_404(Ticket, pk=pk)
    if request.method =="POST":
        project = Project.objects.get(id=ticket.project.id)
        project.status = request.POST['status']
        project.save()

        ticket.status = request.POST['status']
        ticket.save()
    return HttpResponseRedirect(request.POST['redirect_to'])

core/templates/core/dashboard.html
{% extends "base.html" %}

{% block title %}
{{ page_heading }}
{% endblock title %}

{% block content %}    
<div class="align-items-center justify-content-between mb-4">
	<h1 class="h3 mb-0 text-gray-800">{{ page_heading }}</h1>
	<br/>
	{% for project in projects %}        
		<a href="{% url 'core:project-detail' project.id %}" class="btn btn-lg btn-{{ btn_choices|random }} mr-4 mb-4">{{ project.name }}</a>		
	{% endfor %}
	<hr/>
	<br/>
	<a class="btn" href="{% url 'core:ticket-create' %}" style="border: 1px solid #cfcfcf; margin-right: 5px;">
		<i class="fas fa-ticket-alt"></i>
		<span>+ Add Ticket</span>
	</a>
	<a class="btn" href="{% url 'core:user-create' %}" style="border: 1px solid #cfcfcf; margin-right: 5px;">
		<i class="fas fa-user"></i>
		<span>+ Add User</span>
	</a>
	<a class="btn" href="{% url 'core:project-create' %}" style="border: 1px solid #cfcfcf; margin-right: 5px;">
		<i class="fas fa-project-diagram"></i>
        <span>+ Add Project</span>
	</a>
	<a class="btn" href="{% url 'core:projectmember-create' %}" style="border: 1px solid #cfcfcf; margin-right: 5px;">
		<i class="fas fa-users"></i>
		<span>+ Add Project Member</span>
	</a>
</div>
{% endblock content %}

core/templates/core/dashboard2.html
{% extends "base.html" %}

{% block title %}
{{ page_heading }}
{% endblock title %}

{% block content %}    
<div class="align-items-center justify-content-between mb-4">
	<h1 class="h3 mb-0 text-gray-800">{{ page_heading }}</h1>
	<br/>
	{% for project in projects %}        
		<a href="{% url 'core:project-detail' project.id %}" class="btn btn-lg btn-{{ btn_choices|random }} mr-4 mb-4">{{ project.name }}</a>
	{% endfor %}
	<hr/>
	<br/>
	{% if projects %}
	My Ticket
	<div class="row">
		<div class="col-lg-12">
			<table class="table table-bordered table-striped" id="dashboard2Table" width="100%" cellspacing="0">
				<thead>
					<tr>
						<th>Ticket #</th>
						<th>Project</th>
						<th>Initialized on</th>
						<th>Details</th>
						<th>Current Status</th>
						<th class="float-right">Action</th>
					</tr>
				</thead>
				<tbody>
					{% if tickets %}
					{% for ticket in tickets %}
					<tr>
						<td>{{ ticket.id }}</td>
						<td>{{ ticket.project }}</td>
						<td>{{ ticket.date_i }}</td>
						<td>{{ ticket.details}}</td>
						<td align="center">
							{% if ticket.status == 'i' %}
							<p class="btn btn-warning btn-custom-i">Initialized</p>
							{% elif ticket.status == 'w' %}
							<p class="btn btn-primary btn-custom-w">Working</p>
							{% elif ticket.status == 'c' %}
							<p class="btn btn-custom-c">Finished</p>
							{% endif %}
						</td>
						<td>
							<a href="{% url 'core:project-detail' ticket.project.id %}" class="btn btn-primary btn-custom-v float-right"><i class="fas fa-eye" aria-hidden="true"></i> View</a>
							{% if ticket.status == 'i' %}
							<form action="{% url 'core:ticket-update-status' ticket.id %}" method="post">
								{% csrf_token %}
								{{ update_form.id.as_hidden }}
								<input type="hidden" name="id" value="{{ ticket.id }}" />
								<input type="hidden" name="status" value="w" />
								<input type="hidden" name="redirect_to" value="{{ request.path }}" />
								<input type="submit" value="Start" class="btn btn-info btn-input float-right" title="Start working" />
							</form>
							{% elif ticket.status == 'w' %}
							<form action="{% url 'core:ticket-update-status' ticket.id %}" method="post">
								{% csrf_token %}
								<input type="hidden" name="id" value="{{ ticket.id }}" />
								<input type="hidden" name="status" value="c" />
								<input type="hidden" name="redirect_to" value="{{ request.path }}" />
								<input type="submit" value="Complete" class="btn btn-info btn-input float-right" title="Mark complete" />
							</form>
							{% elif ticket.status == 'c' %}
							<p class="btn btn-custom-c float-right disabled" title="No action required">Complete</p>
							{% endif %}
						</td>
					</tr>
					{% endfor %}
					{% else %}
						<tr>
							<td colspan="5" align="center">No data found</td>
						</tr>
					{% endif %}
				</tbody>
			</table>
		</div>
	</div>
	{% endif %}
</div>
{% endblock content %}

core/templates/core/project-detail.html
{% extends "base.html" %}

{% block title %}
{{ project }} Project
{% endblock title %}

{% block content %}
<div class="align-items-center justify-content-between mb-4">	
	<div class="row">
		<div class="col-lg-12">
			<div class="card mb-4 py-3 border-left-info">
				<div class="card-body">
					<h1 class="h3 mb-0 text-gray-800">
						{{ project }}
						<a href="{% url 'core:dashboard' %}?p=1" class="btn btn-secondary float-right">Back</a>					
					</h1>
					<hr/>

					<div class="row custom-row">
						<div class="col-lg-2">
							Project:
						</div>
						<div class="col-lg-10">
							<strong>{{ project }}</strong>
						</div>
					</div>

					<div class="row custom-row">
						<div class="col-lg-2">
							Start Date:
						</div>
						<div class="col-lg-10">
							<strong>{{ project.start_date }}</strong>
						</div>
					</div>

					<div class="row custom-row">
						<div class="col-lg-2">
							End Date:
						</div>
						<div class="col-lg-10">
							{% if expired %}
							<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-exclamation-triangle" viewBox="0 0 16 16">
								<path d="M7.938 2.016A.13.13 0 0 1 8.002 2a.13.13 0 0 1 .063.016.146.146 0 0 1 .054.057l6.857 11.667c.036.06.035.124.002.183a.163.163 0 0 1-.054.06.116.116 0 0 1-.066.017H1.146a.115.115 0 0 1-.066-.017.163.163 0 0 1-.054-.06.176.176 0 0 1 .002-.183L7.884 2.073a.147.147 0 0 1 .054-.057zm1.044-.45a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566z"/>
								<path d="M7.002 12a1 1 0 1 1 2 0 1 1 0 0 1-2 0zM7.1 5.995a.905.905 0 1 1 1.8 0l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995z"/>
							</svg>
							<small >Date Expired</small>
							<br/>
							<strong style="color: #e72424;">{{ project.end_date }}</strong>
							{% else %}
							<strong>{{ project.end_date }}</strong>
							{% endif %}
						</div>
					</div>

					<div class="row custom-row">
						<div class="col-lg-2">
							Status:
						</div>
						<div class="col-lg-10">
							{% if project.status == 'i' %}
								<strong>Initialized</strong>
							{% elif project.status == 'w' %}
								<strong>Working</strong>
							{% elif project.status == 'c' %}
								<strong>Complete</strong>
							{% endif %}
						</div>
					</div>

					<div class="row custom-row">
						<div class="col-lg-2">
							Short Description:
						</div>
						<div class="col-lg-10">
							<strong>{{ project.short_desc }}</strong>
						</div>
					</div>

					<div class="row custom-row">
						<div class="col-lg-2">
							Description:
						</div>
						<div class="col-lg-10">
							<strong>{{ project.description }}</strong>
						</div>
					</div>

					<div class="row custom-row">
						<div class="col-lg-2">
							Members:
						</div>
						<div class="col-lg-10">
							{% for member in members %}
							<a href="{{ meber.id }}" style="margin-right: 5px;"><strong>{{ member.first_name }} {{ member.last_name }}({{ member.username }})</strong></a>
							|
							{% endfor %}
						</div>
					</div>
					<br/>
					<h2 class="h4 mb-4 text-gray-800">
						Ticket
						{% if 'core.add_ticket' in permissions %}	
						<a href="{% url 'core:ticket-create' %}?p=1" class="btn btn-info float-right">+ Add Ticket</a>
						{% endif %}					
					</h2>
					<hr/>					
					<div class="row">
						<div class="col-lg-12">
							<table class="table table-bordered table-striped" id="dataTable" width="100%" cellspacing="0">
								<thead>
									<tr>
										<th>Ticket #</th>
										<th>Member</th>
										<th>Initialized on</th>
										<th>Details</th>
										<th>Status</th>
										<th class="float-right">Action</th>
									</tr>
								</thead>
								<!-- <tfoot>
									<tr>
										<th>Ticket #</th>
										<th>Member</th>
										<th>Initialized on</th>
										<th>Details</th>
										<th>Status</th>
										<th>Action</th>
									</tr>
								</tfoot> -->
								<tbody>
									{% if tickets %}
									{% for ticket in tickets %}
									<tr>
										<td>{{ ticket.id }}</td>
										<td><a href="" style="margin-right: 5px;"><strong>{{ ticket.user.first_name }} {{ ticket.user.last_name }}({{ ticket.user }})</strong></a></td>
										<td>{{ ticket.date_i }}</td>
										<td>{{ ticket.details}}</td>
										<td>
											{% if ticket.status == 'i' %}
												Initialized
											{% elif ticket.status == 'w' %}
												Working
											{% elif ticket.status == 'c' %}
												Complete
											{% endif %}
										</td>
										{% if 'core.delete_ticket' in permissions %}
											<td>
												<a href="/core/ticket/{{ ticket.id }}/delete" class="btn btn-danger float-right" style="padding: 2px 6px;">Delete</a>
											</td>
										{% elif 'core.can_mark_working' in permissions %}
											<td>
												{% if ticket.status == 'i' %}
												<form action="{% url 'core:ticket-update-status' ticket.id %}" method="post">
													{% csrf_token %}
													<input type="hidden" name="id" value="{{ ticket.id }}" />
													<input type="hidden" name="status" value="w" />
													<input type="hidden" name="redirect_to" value="{{ request.path }}" />
													<input type="submit" value="Start" class="btn btn-info float-right" style="padding: 2px 6px; width: 85px;" title="Start working" />
												</form>
												{% elif ticket.status == 'w' %}
												<form action="{% url 'core:ticket-update-status' ticket.id %}" method="post">
													{% csrf_token %}
													<input type="hidden" name="id" value="{{ ticket.id }}" />
													<input type="hidden" name="status" value="c" />
													<input type="hidden" name="redirect_to" value="{{ request.path }}" />
													<input type="submit" value="Complete" class="btn btn-info float-right" style="padding: 2px 6px; width: 85px;" title="Mark complete" />
												</form>
												{% elif ticket.status == 'c' %}
												<p class="btn btn-custom-c float-right disabled" title="No action required">Complete</p>
												{% endif %}
											</td>
										{% endif %}
									</tr>
									{% endfor %}
									{% else %}
										<tr>
											<td colspan="5" align="center">No data found</td>
										</tr>
									{% endif %}
								</tbody>
							</table>
						</div>
					</div>
					
				</div>
			</div>	
        
		</div>
	</div>
</div>
{% endblock content %}

core/templates/core/project_form.html
{% extends "base.html" %}

{% block title %}
Create Project
{% endblock title %}

{% block content %}
    <h1>Create Project</h1>
    {% if messages %}        
    {% for message in messages %}
    <div class="alert alert-info" role="alert">
        {{ message }}
    </div>            
    {% endfor %}
    {% endif %}
    <form action="" method="post">
        {% csrf_token %}
        <table class="table table-bordered" id="addProjectTable" width="100%" cellspacing="0" border="0">
        {{ form.as_table }}
        </table>
        <br/>
        <input type="submit" value="Submit" class="btn btn-primary" />
        <input type="reset" value="Reset" class="btn btn-secondary" />
        {% comment %}<a href="{% url 'core:dashboard' %}" class="btn btn-secondary">Back</a>{% endcomment %}
    </form>
{% endblock %}

core/templates/core/projectmember_form.html
{% extends "base.html" %}

{% block title %}
Create ProjectMember
{% endblock title %}

{% block content %}
    <h1>Create ProjectMember</h1>
    {% if messages %}        
    {% for message in messages %}
    <div class="alert alert-info" role="alert">
        {{ message }}
    </div>            
    {% endfor %}
    {% endif %}
    <form action="" method="post">
        {% csrf_token %}
        <table class="table table-bordered" id="addProjectMemberTable" width="100%" cellspacing="0" border="0">
        {{ form.as_table }}
        </table>
        <br/>
        <input type="submit" value="Submit" class="btn btn-primary" />
        <input type="reset" value="Reset" class="btn btn-secondary" />
        {% comment %}<a href="{% url 'core:dashboard' %}" class="btn btn-secondary">Back</a>{% endcomment %}
    </form>
{% endblock %}

{% block script %}
<script>
    li = document.getElementsByClassName('errorlist')
    text = li[0].innerText.split('\n')
    li[0].innerText = text[1]
    li[0].style.marginBottom = '0px'    
</script>
{% endblock script %}

core/templates/core/ticket_delete.html
{% extends "base.html" %}

{% block title %}
Delete Ticket
{% endblock title %}

{% block content %}
<h1>Delete Ticket</h1>
<p>Are you sure you want to delete the ticket: {{ ticket }}?</p>
<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes, delete." class="btn btn-primary" />
    <input type="hidden" name="redirect_to" value="{{ redirect_url }}" />
    <a href="{{ redirect_url }}" class="btn btn-secondary btn-back">Back</a>
</form>
{% endblock %}

{% block script %}
<script>
    jQuery(function($){
        console.log('hello world');
    })
</script>
{% endblock script %}

core/templates/core/ticket_form.html
{% extends "base.html" %}

{% block title %}
Add Ticket
{% endblock title %}

{% block content %}
    <h1>Add Ticket</h1>
    {% if messages %}        
    {% for message in messages %}
    <div class="alert alert-info" role="alert">
        {{ message }}
    </div>            
    {% endfor %}
    {% endif %}
    <form action="" method="post">
        {% csrf_token %}
        <table class="table table-bordered" id="addTicketTable" width="100%" cellspacing="0" border="0">
        {{ form.as_table }}
        </table>
        <br/>
        <input type="submit" value="Submit" class="btn btn-primary" />
        <input type="reset" value="Reset" class="btn btn-secondary" />
        {% comment %}<a href="{% url 'core:dashboard' %}" class="btn btn-secondary">Back</a>{% endcomment %}
    </form>
{% endblock %}

core/templates/core/user-register.html
{% extends "base.html" %}

{% block title %}
Create User
{% endblock title %}

{% block content %}
    <h1>Create User</h1>
    {% if messages %}        
    {% for message in messages %}
    <div class="alert alert-info" role="alert">
        {{ message }}
    </div>            
    {% endfor %}
    {% endif %}
    <form action="" method="post">
        {% csrf_token %}
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0" border="0">
        {{ form.as_table }}
        </table>
        <br/>
        <input type="submit" value="Submit" class="btn btn-primary" />
        <input type="reset" value="Reset" class="btn btn-secondary" />
        {% comment %}<a href="{% url 'core:dashboard' %}" class="btn btn-secondary">Back</a>{% endcomment %}
    </form>
{% endblock %}