core/urls.py
from django.urls import path
from django.views.generic import RedirectView

from .views import dashboard, UserCreate, ProjectCreate, ProjectMemberCreate, TicketCreate, project_detail, delete_ticket, update_ticket_status

app_name = 'core'

urlpatterns = [
    path('', RedirectView.as_view(url='dashboard/')),
    path('dashboard/', dashboard, name='dashboard'),
]

urlpatterns += [
    path('user/create/', UserCreate, name='user-create'),
]

urlpatterns += [
    path('project/create/', ProjectCreate.as_view(), name='project-create'),
    path('projectmember/create/', ProjectMemberCreate.as_view(), name='projectmember-create'),
    path('ticket/create/', TicketCreate.as_view(), name='ticket-create'),
    path('project/<int:pk>', project_detail, name='project-detail'),
    path('ticket/<str:pk>/delete', delete_ticket, name='ticket-delete'),
    path('ticket/<str:pk>/update-status', update_ticket_status, name='ticket-update-status'),
]

sms/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView
from .views import login_view, logout_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='/login/')),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('core/', include('core.urls', namespace='core')),
]

admin.site.site_header = 'SMS'

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />

    <!-- favicon --> 
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" />

    <!-- Custom fonts for this template-->
    <link href="{% static 'fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css" />
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet" />

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet" />
    <link href="{% static 'css/style.css' %}" rel="stylesheet" />    

    <title>{% block title %}{% endblock title %} &mdash; Software Management System</title>
</head>
<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">
        {% include 'sidemenu.html' %}
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                {% include 'topmenu.html' %}

                <!-- Begin Page Content -->
                <div class="container-fluid">
					{% block content %}
                    {% endblock content %}
                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; SMS 2021</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>    

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'js/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'js/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin-2.min.js' %}"></script>
    {% block script %}
    {% endblock script %}
</body>
</html>

templates/sidemenu.html
{% load static %}
{% url 'core:dashboard' as dashboard %}
{% url 'core:user-create' as create_user %}
{% url 'core:project-create' as create_project %}
{% url 'core:projectmember-create' as create_projectmember %}
{% url 'core:ticket-create' as create_ticket %}


<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
    <!-- Sidebar - Brand -->
    <img src="{% static 'img/logo-small.jpeg' %}" title="Software Management System :: A Ticketing Software" style="height:70px;" />
    <!-- <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
        <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3">SB Admin <sup>2</sup></div>
    </a> -->

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item {% if request.resolver_match.url_name == 'dashboard' %}active{% endif %}">
        <a class="nav-link" href="{{ dashboard }}">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Dashboard</span></a>
    </li>
	{% if 'auth.add_user' in permissions %}
    <!-- Divider -->
    <hr class="sidebar-divider my-0">
	
	<!-- Nav Item - Add User -->
    <li class="nav-item {% if request.resolver_match.url_name == 'user-create' %}active{% endif %}">
        <a class="nav-link" href="{{ create_user }}">
            <i class="fas fa-user"></i>
            <span>+ Add User</span></a>
    </li>
	{% endif %}
	{% if 'core.add_projectmember' in permissions %}
	<!-- Divider -->
    <hr class="sidebar-divider my-0">
	
	<!-- Nav Item - Add Member -->
    <li class="nav-item {% if request.resolver_match.url_name == 'projectmember-create' %}active{% endif %}">
        <a class="nav-link" href="{{ create_projectmember }}">
            <i class="fas fa-users"></i>
            <span>+ Add Member</span></a>
    </li>
	{% endif %}
    {% if 'core.add_project' in permissions %}
    <!-- Divider -->
    <hr class="sidebar-divider my-0">
    <li class="nav-item {% if request.resolver_match.url_name == 'project-create' %}active{% endif %}">
        <a class="nav-link" href="{{ create_project }}">
            <i class="fas fa-project-diagram"></i>
            <span>+ Add Project</span></a>
    </li>
    {% endif %}
    {% if 'core.add_ticket' in permissions %}
    <!-- Divider -->
    <hr class="sidebar-divider my-0">
    <li class="nav-item {% if request.resolver_match.url_name == 'ticket-create' %}active{% endif %}">
        <a class="nav-link" href="{{ create_ticket }}">
            <i class="fas fa-ticket-alt"></i>
            <span>+ Add Ticket</span></a>
    </li>
    {% endif %}
    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
        Interface
    </div>

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
            aria-expanded="true" aria-controls="collapseTwo">
            <i class="fas fa-fw fa-cog"></i>
            <span>Projects</span>
        </a>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Projects:</h6>
                <a class="collapse-item" href="{{ dashboard }}?p=1">My Projects</a>
                {% if 'core.add_project' in permissions %}
                <a class="collapse-item" href="{{ create_project }}">+ Add Project</a>
                {% endif %}
            </div>
        </div>
    </li>                   

    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>
</ul>
<!-- End of Sidebar -->

templates/topmenu.html
{% load static %}
{% url 'logout' as logout%}
<!-- Topbar -->
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>
    
    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">

        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
        <li class="nav-item dropdown no-arrow d-sm-none">
            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-search fa-fw"></i>
            </a>
            <!-- Dropdown - Messages -->
            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                aria-labelledby="searchDropdown">
                <form class="form-inline mr-auto w-100 navbar-search">
                    <div class="input-group">
                        <input type="text" class="form-control bg-light border-0 small"
                            placeholder="Search for..." aria-label="Search"
                            aria-describedby="basic-addon2">
                        <div class="input-group-append">
                            <button class="btn btn-primary" type="button">
                                <i class="fas fa-search fa-sm"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </li>                  

        <div class="topbar-divider d-none d-sm-block"></div>

        <!-- Nav Item - User Information -->
        <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{user.first_name}} {{user.last_name}}<br/><small style="color: green;">{{profile.designation}}</small></span>
                {%  if profile.sex == 'm' %}
                <img class="img-profile rounded-circle" src="{% static 'img/pic-male.svg' %}" />
                {% else %}
                <img class="img-profile rounded-circle" src="{% static 'img/pic-female.svg' %}" />
                {% endif %}
                
            </a>
            <!-- Dropdown - User Information -->
            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                aria-labelledby="userDropdown">
                <a class="dropdown-item" href="#">
                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                    Profile
                </a>
                <a class="dropdown-item" href="#">
                    <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                    Settings
                </a>
                <a class="dropdown-item" href="#">
                    <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                    Activity Log
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{{ logout }}">
                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                    Logout
                </a>
            </div>
        </li>

    </ul>

</nav>
<!-- End of Topbar -->